dev-in-docker: bugfixes and features
* migrate|frontend|backend: run in pipenv (bugfix)
* bin/dev-in-docker clean: wipe volumes and saved data
* bin/dev-in-docker sql|test-sql: open a psql prompt
* bin/dev-in-docker start: rebuild images (in case deps change)
* bin/dev-in-docker start: run `npm install`

diff --git a/bin/dev-in-docker b/bin/dev-in-docker
--- a/bin/dev-in-docker
+++ b/bin/dev-in-docker
@@ -40,44 +40,82 @@ print_usage() {
   echo "Usage: $0 COMMAND ARGS..." >&2
   echo >&2
   echo 'Where COMMAND is one of:' >&2
-  echo '  develop-module DIR URL -- runs "./manage.py develop-module ARGS..."' >&2
-  echo '  npm ARGS -- runs "npm ARGS..." in a Node environment' >&2
-  echo '  pipenv ARGS -- runs "pipenv ARGS..." in a Python environment' >&2
-  echo '  python ARGS -- runs "pipenv run python ARGS..." in a Python environment' >&2
-  echo '  start -- starts database, Redis, Webpack and Python' >&2
-  echo '  stop -- stops services created by start' >&2
-  echo '  unittest ARGS -- runs "./manage.py test ARGS..."' >&2
-  echo '  run SERVICE ARGS -- runs "docker-compose run -rm SERVICE ARGS..."' >&2
+  echo '  clean -- wipe all data' >&2
+  echo '  develop-module DIR URL -- run "./manage.py develop-module ARGS..."' >&2
+  echo '  npm ARGS -- run "npm ARGS..." in a Node environment' >&2
+  echo '  pipenv ARGS -- run "pipenv ARGS..." in a Python environment' >&2
+  echo '  python ARGS -- run "pipenv run python ARGS..." in a Python environment' >&2
+  echo '  run SERVICE ARGS -- run "docker-compose run -rm SERVICE ARGS..."' >&2
+  echo '  sql -- open a psql prompt in the dev database (it must be up)' >&2
+  echo '  start -- start database, Redis, Webpack and Django' >&2
+  echo '  stop -- stop services created by start' >&2
+  echo '  test-sql -- open a psql prompt in the test database (it must be up)' >&2
+  echo '  unittest ARGS -- run "./manage.py test ARGS..."' >&2
 }
 
-case "$1" in
+COMMAND="$1"
+shift
+
+case "$COMMAND" in
+  "clean")
+    # Delete all files.
+    #
+    # Why use docker? Because files written by Docker are owned by root, so
+    # `rm local_mail/*` will fail if we run outside of Docker.
+    #
+    # Why use docker-compose instead of, say, `docker run --rm alpine:3.8`?
+    # Because mounting this directory as a volume requires an absolute path,
+    # and finding the absolute path takes different logic on Windows than on
+    # non-Windows.
+    #
+    # docker-compose is much slower, but it takes fewer lines of code.
+    docker_compose run --rm frontend rm -rf local_mail/* importedmodules/* media/* node_modules/
+
+    # Wipe volumes
+    docker_compose_with_commands down -t0 -v # -v removes named volumes
+    docker_compose_with_commands rm -f -v # -v removes _anonymous_ volumes
+    ;;
+
   "npm")
-    shift
     docker_compose run --rm webpack npm "$@"
     ;;
 
   "python")
-    shift
     docker_compose run --rm frontend pipenv run python "$@"
     ;;
 
   "pipenv")
-    shift
     docker_compose run --rm frontend pipenv "$@"
     ;;
 
   "unittest")
-    shift
     docker_compose_with_commands run --rm unittest pipenv run python ./manage.py test "$@"
     ;;
 
   "develop-module")
-    echo 'FIXME gotta re-develop this one to work with docker-compose somehow' >&2
+    echo 'FIXME gotta re-develop this command to work with docker-compose somehow' >&2
     exit 1
     ;;
 
+  "sql")
+    docker_compose exec database psql -U cjworkbench "$@"
+    ;;
+
+  "test-sql")
+    docker_compose exec testdatabase psql -U cjworkbench "$@"
+    ;;
+
   "start")
+    # Make sure every dev has the same versions of Python/Node by pulling
+    docker_compose_with_commands build --pull
+
+    # Make sure Python deps are up to date; migrate database
     docker_compose_with_commands run --rm migrate
+
+    # Make sure JavaScript deps are up to date
+    docker_compose run --rm webpack npm install
+
+    # Start Django and Webpack
     docker_compose up
     ;;
 
@@ -87,7 +125,6 @@ case "$1" in
     ;;
 
   "run")
-    shift
     docker_compose_with_commands run --rm "$@"
     ;;
 
